name: Build and Test no-std Demos

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  demos-nostd:
    name: "Build all no-std demos"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-toolchain:
          - nightly
          - stable
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust-toolchain }}
          targets: thumbv6m-none-eabi, thumbv7em-none-eabi, thumbv8m.main-none-eabihf, riscv32imac-unknown-none-elf
          components: rust-src
      #
      # microbit demos
      #
      - name: Build microbit Demos
        working-directory: ./demos/microbit
        run: cargo build --all
      #
      # nRF52840 demos
      #
      - name: Build nRF52840 Demos
        working-directory: ./demos/nrf52840
        run: cargo build --all
      #
      # RP2040 demos
      #
      - name: Build RP2040 Demos
        working-directory: ./demos/rp2040
        run: cargo build --all
      #
      # RP2350 demos
      #
      - name: Build RP2350 Demos
        working-directory: ./demos/rp2350
        run: cargo build --all
      #
      # ESP32C3 demos
      #
      - name: Check ESP32C3 Demos
        working-directory: ./demos/esp32c3
        run: cargo build --all
      #
      # ESP32C6 demos
      #
      - name: Check ESP32C6 Demos
        working-directory: ./demos/esp32c6
        run: cargo build --all
      #
      # STM32F303 demos
      #
      - name: Check STM32F303 Demos
        working-directory: ./demos/stm32f303vc
        run: cargo build --all
      #
      # Shared ICD
      #
      - name: Check shared icd
        working-directory: ./demos/shared-icd
        run: cargo build --target=thumbv7em-none-eabi
