name: Build and Test no-std Demos

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  demos-nostd:
    name: "Build all no-std demos"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install thumbv7em target
        run: rustup target add thumbv7em-none-eabi
      - name: Install thumbv6m target
        run: rustup target add thumbv6m-none-eabi
      - name: Install riscv32imac target
        run: rustup target add riscv32imac-unknown-none-elf
      - name: Install thumbv8m target
        run: rustup target add thumbv8m.main-none-eabihf
      #
      # nRF52840 demos
      #
      - name: Build nRF52840 Demos
        working-directory: ./demos/nrf52840
        run: cargo build --all
      #
      # RP2040 demos
      #
      - name: Build RP2040 Demos
        working-directory: ./demos/rp2040
        run: cargo build --all
      #
      # RP2350 demos
      #
      - name: Build RP2350 Demos
        working-directory: ./demos/rp2350
        run: cargo build --all
      #
      # ESP32C6 demos
      #
      - name: Check ESP32C6 Demos
        working-directory: ./demos/esp32c6
        run: cargo build --all
