name: Build and Test Std Demos

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  demos-std:
    name: "Build all std demos"
    strategy:
      matrix:
        os:
          - windows-2022
          - ubuntu-latest
          - macos-14
        rust-toolchain:
          - nightly
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust-toolchain }}
      #
      # STD demos
      #
      - name: Check std demos
        working-directory: ./demos/std
        run: cargo build --all
      #
      # Shared ICD
      #
      - name: Check shared icd
        working-directory: ./demos/shared-icd
        run: cargo build
